baseURL = "https://weirdloop.org"
languageCode = "en-us"
title = "Cesar Alvernaz"

theme = "hugo-coder-portfolio"

# Theme paramter
[params]
  author = "Cesar Alvernaz" # Author's name.
  info = "Freelance software engineer" # Author's job title or info.
  description = "Weirdloop's website" # Site description.
  keywords = "blog,developer,personal" # Site keywords.
  avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.
  
  hireMe = true
  hireMeStatus = "Unavailable" # Unavailable

  hideCredits = true
  hideCopyright = true

  #footercontent = "Hire me!" # Add footer content
  #fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
  #fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/calvernaz/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/calvernaz/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/cesaralvernaz/"


# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "posts"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "about"